service:
  name: interview-prep
  version: v0.1.0-test

logger:
  disable: true
  level: error
  encoding: pretty

tracing:
  disable: true
  exporter_host: localhost
  exporter_port: 4317

alert:
  provider: noop

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: test_interview-prep # IMPORTANT

kafka_broker:
  brokers: localhost:9092

redis:
  addrs: 127.0.0.1:6379

http_server:
  host: localhost
  port: 9876

cors:
  enabled: true
  allow_origins:
    - http://localhost:3000
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - X-Requested-With
  expose_headers:
    - X-Trace-ID
  allow_credentials: true
  max_age: 86400

# Module specific configs

auth:
  mail:
    provider: noop
  frontend_verify_email_url: http://localhost:3000/verify-email
  frontend_password_reset_url: http://localhost:3000/password-reset
  email_verification_token_ttl: 24h
  password_reset_token_ttl: 30m
  google_oauth:
    enabled: false
  github_oauth:
    enabled: false
  access_token_ttl: 24h
  refresh_token_ttl: 168h # 7 days
  max_active_sessions: 5
  worker_poll_interval: 100ms
  hashing_cost: 4 # low cost for fast tests

filevault:
  max_file_size_mb: 10
  minio:
    endpoint: localhost:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: interview-prep

audit:
  worker_poll_interval: 100ms

platform:
  worker_poll_interval: 100ms
  alert_schema: alert
